---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by fangjinuo.
--- DateTime: 2021/3/5 18:02
---

ngx.log(ngx.INFO, "content by lua")
local client_socket, get_socket_err = ngx.req.socket(true)
if (not client_socket) then
    ngx.log(ngx.ERROR, "unable to get client socket", get_socket_err)
    return
end
-- write welcome information
local write_ok, write_err = client_socket:send("welcome to the openresty telnet service:\n")
if (not write_ok) then
    ngx.log(ngx.ERROR, "write message fail", write_err)
end


-- start a thread to read and write
local task = function()
    while (true) do
        -- read a line
        local message, read_err = client_socket:receive("*l")
        if (not read_err) then
            ngx.log(ngx.INFO, "read: [" .. message .. "]");
            -- write
            local time = ngx.localtime();
            local write_byte_num, write_err = client_socket:send("response: " .. time .. " " .. message);
            if (write_err) then
                ngx.exit(500)
            end
        else
            ngx.exit(400)
        end
    end
end

local threadId = ngx.thread.spawn(task)






