---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by fangjinuo.
--- DateTime: 2021/2/26 15:36
---



print(package.path)
package.path = package.path .. ";D:/projects/workspace_langx_lua/langx_lua/src/main/lua/?.lua"

require("debugger")

print(package.path)

print(_VERSION)

local globalEnvVariables = _G
print(_G)

local Collects = require("collection.Collects")
Collects.forEach(_G, nil, function(key, value)
        print(key, value)
    end
)

globalEnvVariables = _G
print(_G)