---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by fangjinuo.
--- DateTime: 2021/2/24 19:55
---
---
---

require("debugger")

print("hello world")

-- n!
function fact(n)
    if n==0 then
        return 1
    else
        return n * fact(n-1)
    end
end

print ("enter a number:")
a = io.read("*number")
print(235,a);
print(fact(a))