---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by fangjinuo.
--- DateTime: 2021/3/1 10:47
---
require("debugger")
package.path = package.path .. ";D:/projects/workspace_langx_lua/langx_lua/src/main/lua/?.lua"

local Pipeline = require("collection.Pipeline")
local Types = require("Types")

local tb = { "a1", "a2", 3, "a4", 'a5' }

local pipeline = Pipeline:new(tb)

pipeline:filter(
        function(index, value)
            return Types.isString(value)
        end
)       :forEach(nil,
        function(index, value)
            print(index, value)
        end
)





