---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by fangjinuo.
--- DateTime: 2021/3/1 10:47
---
require("debugger")
package.path = package.path .. ";D:/projects/workspace_langx_lua/langx_lua/src/main/lua/?.lua"

local Pipeline = require("collection.Pipeline")
local Objs = require("Objs")

function showTable(tb)
    local pipeline = Pipeline:new(tb)

    pipeline:filter(
            function(index, value)
                return Objs.isString(value)
            end
    )       :forEach(
            function(index, value)
                print(index, value)
            end
    )
end

print("===========test 1=============")
local tb1 = { "a1", "a2", 3, "a4", 'a5' }
showTable(tb1)
print("===========test 2=============")
local tb2 = {
    key1 = "value1",
    key2 = "value2",
    key3 = "value3",
    key4 = "value4",
    key5 = "value5"
}
showTable(tb2)



