---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by fangjinuo.
--- DateTime: 2021/3/1 11:46
---
require("debugger")
package.path = package.path .. ";D:/projects/workspace_langx_lua/langx_lua/src/main/lua/?.lua"

local a = "abc123,23a12,dadf"
local pattern = "%d+"
local generator = string.gmatch(a, pattern)
local Pipeline = require("collection.Pipeline")

Pipeline:new(generator):map(function(index, value)
    return index, tonumber(value)
end)    :filter(function(index, value)
    return value > 10
end)    :forEach(function(index, value)
    print(index, value)
end)
