---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by fangjinuo.
--- DateTime: 2021/2/26 14:14
---

-- test nil
local a = nil
print(a, type(a))

-- test boolean
print("nil is false: \t", a==false)
print("false is false: \t", false == false)
print("0 is false: \t", 0==false)
print("true type: ", type(true))

print("type 1 : ", type(1))
print("type {} : ", type({}))


-- test number

-- @param a {number}
function testIfElse(a)

end


