---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by fangjinuo.
--- DateTime: 2021/2/26 14:31
---

local Types = {};

function Types.isNull(obj)
    return obj == nil
end

function Types.isNotNull(obj)
    return not isNull(obj)
end

function Types.isString(obj)
    return "string" == type(obj)
end

function Types.isNumber(obj)
    return "number" == type(obj)
end

function Types.isBoolean(obj)
    return "boolean" == type(obj)
end

function Types.isFunction(obj)
    return "function" == type(obj)
end

function Types.isTable(obj)
    return "table" == type(obj)
end

return Types;