---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by fangjinuo.
--- DateTime: 2021/3/1 16:22
---

local StringTemplate = {
    template = "",
    variablePattern = "{}",
    variableGetter = function(matched)
        return nil
    end
}

function StringTemplate:new()
    local o = {}
    setmetatable(o, self)
    self.__index = self
    return o
end

function StringTemplate:format()
    local formatted, num = string.gsub(self.template, self.variablePattern, self.variableGetter)
    return formatted
end

return StringTemplate;