---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by fangjinuo.
--- DateTime: 2021/2/26 16:14
---

local Functions = {}

function Functions.truePredicate()
    return true
end

function Functions.falsePredicate()
    return false
end

function Functions.noopFunction(any)
    return any
end

return Functions;