---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by fangjinuo.
--- DateTime: 2021/2/26 14:31
---

local Objs = {};

function Objs.isNull(obj)
    return obj == nil
end

function Objs.isNotNull(obj)
    return not isNull(obj)
end

function Objs.isString(obj)
    return "string" == type(obj)
end

function Objs.isNumber(obj)
    return "number" == type(obj)
end

function Objs.isBoolean(obj)
    return "boolean" == type(obj)
end

function Objs.isFunction(obj)
    return "function" == type(obj)
end
--- judge whether an obj is a table or not
function Objs.isTable(obj)
    return "table" == type(obj)
end

--- use a value if match the predicate
--- @param obj any
--- @param predicate function
--- @param replacement any | function
function Objs.useValueIfMatch(obj, predicate, replacement)
    if (predicate(obj)) then
        if (Objs.isFunction(replacement)) then
            return replacement()
        else
            return replacement
        end
    end
    return obj
end

function Objs.useValueIfNull(obj, replacement)
    return Objs.useValueIfMatch(obj, function(o)
        return o == nil;
    end, replacement)
end

return Objs;