---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by fangjinuo.
--- DateTime: 2021/3/5 14:08
---

local Array = { length = 0, tb = {} }

function Array:new(tb)
    tb = tb or {}
    local instance = {}
    setmetatable(instance, self)
    self.__index = self
    instance.tb = tb
    instance.length = rawlen(tb)
    return instance
end

function Array:size()
    return self.length
end

function Array:isEmpty()
    return self:size() == 0
end

function Array:add(e)
    self.tb[self:size() + 1] = e
end

function Array:remove(e)

end